extends Node

enum itemType {GENERIC, EQUIPMENT, CONSUMABLE, QUEST}
enum equipmentSlot {HEAD, FACE, TORSO, CHEST, LEGS, WAIST, FEET, ANKLE}
enum statType {TOUGH, COOL, PUNK, GOTH, PREP, CUTE, SPORTY}
