extends Node

enum itemType {GENERIC, CLOTHING, CONSUMABLE, QUEST}
enum equipmentSlot {HEAD, FACE, TORSO, CHEST, LEGS, WAIST, FEET, ANKLE}
enum STYLES {TOUGH, COOL, PUNK, GOTH, PREP, CUTE, SPORTY}
enum attributeType {MIGHT, HARDY, AGILITY, AWARE, INTEL, SPIRIT, WILL, LUCK} 
enum partType {HEAD, TORSO, WAIST, LEGS, FEET, ARMS, HANDS}
enum MOOD {OKAY, HAPPY, SAD, ANGRY}
