extends Node

enum ITEMS {EQUIPABLE}

enum STYLES {TOUGH, COOL, PUNK, GOTH, PREP, CUTE, SPORTY, SEXY, NERD}
enum ABILITIES {MIGHT, HARDY, AGILITY, AWARE, INTEL, SPIRIT, WILL, LUCK, FAME, ACCEPT}
enum REPS {SMART_DUMB, STYLISH_SLOB, NORMAL_WEIRD, WEAK_STRONG}

enum PARTS {HEAD, TORSO, WAIST, LEGS, FEET, ARMS, HANDS}

enum MOODS {OKAY, HAPPY, SAD, ANGRY}

enum SLOTS {ACCESSORY, HEAD, TORSO, LEGS, FEET, HANDS}
enum COVERAGE {COMPLETE = 9, SOME = 6,LITTLE = 3, NONE = 1}

var GRAV : float = 29.0
